In [24]:
import geopandas as gpd
import os
import matplotlib.pyplot as plt

In [50]:
def path_list():
    path_municipios = os.getcwd()+'./arquivos_vetoriais/municipios.shp'
    path_aeroportos = os.getcwd()+'./arquivos_vetoriais/aeroportos.shp'
    path_rodovias = os.getcwd()+'./arquivos_vetoriais/rodovias.shp'

    return [path_municipios, path_aeroportos, path_rodovias]

def open_shapefile():

    return [gpd.read_file(i) for i in path_list()]

def filter_municipios(state, shapes):

    return municipios[municipios['uf'] == state]

def run(state):
    shapes = open_shapefile()
    municipio_filter = filter_municipios(state, shapes[0])
    return municipio_filter

In [51]:
run('AL')

,id,id_pk,geocodigo,municipio,uf,regiao,area,geometry
42,43,528,2705408,Monteirópolis,AL,Nordeste,None,"POLYGON ((-37.24281 -9.60120, -37.23575 -9.612..."
48,49,529,2705507,Murici,AL,Nordeste,None,"POLYGON ((-35.95552 -9.21410, -35.88857 -9.138..."
71,72,483,2701308,Cajueiro,AL,Nordeste,None,"POLYGON ((-36.17889 -9.35934, -36.17852 -9.358..."
95,96,536,2706208,Palestina,AL,Nordeste,None,"POLYGON ((-37.33204 -9.66920, -37.31784 -9.660..."
97,98,526,2705200,Messias,AL,Nordeste,None,"POLYGON ((-35.84987 -9.36239, -35.83009 -9.322..."
...,...,...,...,...,...,...,...,...
2479,2474,567,2709004,Tanque D'Arca,AL,Nordeste,None,"POLYGON ((-36.37912 -9.56852, -36.37953 -9.571..."
2480,2475,568,2709103,Taquarana,AL,Nordeste,None,"POLYGON ((-36.57019 -9.56534, -36.57059 -9.564..."
2481,2476,569,2709152,Teotônio Vilela,AL,Nordeste,None,"POLYGON ((-36.45077 -9.96098, -36.39883 -9.888..."
2482,2477,571,2709301,União Dos Palmares,AL,Nordeste,None,"POLYGON ((-36.03134 -9.05645, -36.03073 -9.056..."
2485,2479,572,2709400,Viçosa,AL,Nordeste,None,"POLYGON ((-36.18471 -9.37624, -36.21112 -9.453..."